package types

// AIModel represents a Gemini AI model
type AIModel struct {
	Name        string `json:"name"`
	DisplayName string `json:"displayName,omitempty"`
	Description string `json:"description,omitempty"`
	Version     string `json:"version,omitempty"`
}

func (m *AIModel) Headers() []string {
	return []string{"Model Name", "Display Name", "Version"}
}

func (m *AIModel) Rows() [][]string {
	return [][]string{{
		truncateID(m.Name, 40),
		m.DisplayName,
		m.Version,
	}}
}

func (m *AIModel) EmptyMessage() string {
	return "No model information available"
}

// AIContent represents content generated by the AI
type AIContent struct {
	Text         string `json:"text"`
	Role         string `json:"role"`
	FinishReason string `json:"finishReason,omitempty"`
}

func (c *AIContent) Headers() []string {
	return []string{"Role", "Text"}
}

func (c *AIContent) Rows() [][]string {
	text := c.Text
	if len(text) > 80 {
		text = text[:77] + "..."
	}
	return [][]string{{
		c.Role,
		text,
	}}
}

func (c *AIContent) EmptyMessage() string {
	return "No content generated"
}

// AIModelsListResponse represents a list of AI models
type AIModelsListResponse struct {
	Models        []AIModel `json:"models"`
	NextPageToken string    `json:"nextPageToken,omitempty"`
}

func (r *AIModelsListResponse) Headers() []string {
	return []string{"Model Name", "Display Name", "Version"}
}

func (r *AIModelsListResponse) Rows() [][]string {
	rows := make([][]string, len(r.Models))
	for i, model := range r.Models {
		rows[i] = []string{
			truncateID(model.Name, 40),
			model.DisplayName,
			model.Version,
		}
	}
	return rows
}

func (r *AIModelsListResponse) EmptyMessage() string {
	return "No models found"
}

// AIGenerateContentResponse represents a content generation response
type AIGenerateContentResponse struct {
	Contents []AIContent `json:"contents"`
	Usage    *AIUsage    `json:"usage,omitempty"`
}

func (r *AIGenerateContentResponse) Headers() []string {
	return []string{"Role", "Text"}
}

func (r *AIGenerateContentResponse) Rows() [][]string {
	rows := make([][]string, len(r.Contents))
	for i, content := range r.Contents {
		text := content.Text
		if len(text) > 80 {
			text = text[:77] + "..."
		}
		rows[i] = []string{
			content.Role,
			text,
		}
	}
	return rows
}

func (r *AIGenerateContentResponse) EmptyMessage() string {
	return "No content generated"
}

// AIUsage represents token usage information
type AIUsage struct {
	PromptTokens     int32 `json:"promptTokens"`
	CompletionTokens int32 `json:"completionTokens"`
	TotalTokens      int32 `json:"totalTokens"`
}
