version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    # Baseline "industry standard" Go checks.
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - misspell
    - unparam
    - errorlint

  settings:
    misspell:
      # Words used intentionally in CLI context.
      ignore-rules:
        - cancelled
        - cancelling

  exclusions:
    rules:
      # Pre-existing unparam issues - would require significant API changes
      - linters: [unparam]
        text: "is unused"
      - linters: [unparam]
        text: "is never used"
      - linters: [unparam]
        text: "always receives"
      - linters: [unparam]
        text: "always nil"
